<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-105EU33" failures="2" tests="7" name="Test" time="92.552" errors="0" timestamp="2025-05-19T11:47:20 MST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="14.292"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.046">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at qa.stepDefinitions.tc2StepDefinition.validate_first_entry_name_is(tc2StepDefinition.java:62)
at ✽.validate first entry name is "A Wave From It All"(file:///C:/Users/mengj/Documents/QA_Projects/OneOak/src/test/resources/featureFiles/TestCase2.feature:13)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="13.576"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="13.744"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="13.626"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="9.693">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at qa.stepDefinitions.tc4StepDefinition.validate_on_home_page(tc4StepDefinition.java:46)
at ✽.validate "CHANDLER VACATION RENTALS" on home page(file:///C:/Users/mengj/Documents/QA_Projects/OneOak/src/test/resources/featureFiles/TestCase4.feature:9)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="9.35"/>
</testsuite> <!-- Test -->
